{{- range $instance := .Values.relay.instances -}}
{{- if $instance.stun.enabled -}}
{{- $context := dict "root" $ "instance" $instance -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}-stun
  namespace: {{ include "netbird.namespace" $ }}
  labels:
    {{- include "netbird.relay.labels" $context | nindent 4 }}
spec:
  type: {{ $instance.stun.service.type }}
  {{- if and (eq $instance.stun.service.type "LoadBalancer") $instance.stun.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $instance.stun.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    {{- range $port := $instance.stun.ports }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: UDP
      name: stun-{{ $port }}
    {{- end }}
  selector:
    {{- include "netbird.relay.selectorLabels" $context | nindent 4 }}
{{- end -}}
{{- end -}}
