{{- range $instance := .Values.relay.instances -}}
{{- $context := dict "root" $ "instance" $instance -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
  namespace: {{ include "netbird.namespace" $ }}
  labels:
    {{- include "netbird.relay.labels" $context | nindent 4 }}
spec:
  type: {{ $instance.service.type }}
  ports:
    - port: {{ $instance.service.port }}
      targetPort: {{ $instance.service.name | default "http" }}
      protocol: TCP
      name: {{ $instance.service.name | default "http" }}
    {{- if $instance.metrics.enabled }}
    - port: {{ $instance.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "netbird.relay.selectorLabels" $context | nindent 4 }}
{{- end -}}
