{{- range $i, $instance := .Values.relay.instances -}}
{{- if $i }}
---
{{- end -}}
{{- $context := dict "root" $ "instance" $instance -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
  namespace: {{ include "netbird.namespace" $ }}
  labels:
    {{- include "netbird.relay.labels" $context | nindent 4 }}
spec:
  type: {{ dig "service" "type" "ClusterIP" $instance }}
  ports:
    - port: {{ dig "service" "port" 33080 $instance }}
      targetPort: {{ dig "service" "name" "http" $instance }}
      protocol: TCP
      name: {{ dig "service" "name" "http" $instance }}
    {{- if dig "metrics" "enabled" false $instance }}
    - port: {{ dig "metrics" "port" 9090 $instance }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "netbird.relay.selectorLabels" $context | nindent 4 }}
{{- end -}}
