{{- $first := true -}}
{{- range $instance := .Values.relay.instances -}}
{{- $ingress := $instance.ingress | default dict -}}
{{- if $ingress.enabled -}}
{{- if not $first }}
---
{{ end -}}
{{- $first = false -}}
{{- $context := dict "root" $ "instance" $instance -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
  namespace: {{ include "netbird.namespace" $ }}
  labels:
    {{- include "netbird.relay.labels" $context | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className | quote }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- toYaml $ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
                port:
                  number: {{ ($instance.service | default dict).port | default 33080 }}
          {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
