{{- range $i, $instance := .Values.relay.instances -}}
{{- if $i }}
---
{{ end -}}
{{- $context := dict "root" $ "instance" $instance -}}
{{- $service := $instance.service | default dict -}}
{{- $metrics := $instance.metrics | default dict -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
  namespace: {{ include "netbird.namespace" $ }}
  labels:
    {{- include "netbird.relay.labels" $context | nindent 4 }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    - port: {{ $service.port | default 33080 }}
      targetPort: {{ $service.name | default "http" }}
      protocol: TCP
      name: {{ $service.name | default "http" }}
    {{- if $metrics.enabled }}
    - port: {{ $metrics.port | default 9090 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "netbird.relay.selectorLabels" $context | nindent 4 }}
  {{- with $service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
