{{- range $i, $instance := .Values.relay.instances -}}
{{- if $i }}
---
{{- end -}}
{{- $context := dict "root" $ "instance" $instance -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
  namespace: {{ include "netbird.namespace" $ }}
  {{- with $instance.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbird.relay.labels" $context | nindent 4 }}
spec:
  replicas: {{ dig "replicaCount" 1 $instance }}
  selector:
    matchLabels:
      {{- include "netbird.relay.selectorLabels" $context | nindent 6 }}
  template:
    metadata:
      {{- with $instance.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netbird.relay.selectorLabels" $context | nindent 8 }}
    spec:
      {{- with $.Values.relay.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird.relay.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.relay.podSecurityContext | nindent 8 }}
      {{- with $instance.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-relay-{{ $instance.name }}
          securityContext:
            {{- toYaml $.Values.relay.securityContext | nindent 12 }}
          image: "{{ $.Values.relay.image.repository }}:{{ $.Values.relay.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.relay.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ dig "containerPort" 33080 $instance }}
              protocol: TCP
            {{- if dig "metrics" "enabled" false $instance }}
            - name: metrics
              containerPort: {{ dig "metrics" "port" 9090 $instance }}
              protocol: TCP
            {{- end }}
          {{- if dig "stun" "enabled" false $instance }}
            {{- range $port := $instance.stun.ports }}
            - name: stun-{{ $port }}
              containerPort: {{ $port }}
              protocol: UDP
            {{- end }}
            {{- end }}
          {{- if $instance.livenessProbe }}
          livenessProbe:
            {{- toYaml $instance.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $instance.readinessProbe }}
          readinessProbe:
            {{- toYaml $instance.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $.Values.relay.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- if $instance.volumeMounts }}
          {{- $instance.volumeMounts | toYaml | nindent 12 }}
          {{- end }}
          {{- if or $.Values.relay.gracefulShutdown $.Values.relay.lifecycle }}
          lifecycle:
            {{- if $.Values.relay.gracefulShutdown }}
            preStop:
              exec:
                command: ["sh", "-c", "echo Waiting 5 seconds to allow terminating current connections >/proc/1/fd/1; sleep 5"]
            {{- end }}
            {{- with $.Values.relay.lifecycle }}
            {{- if .postStart }}
            postStart:
              {{- toYaml .postStart | nindent 14 }}
            {{- end }}
            {{- end }}
          {{- end }}
          env:
          {{- if or ($instance.env) ($instance.envRaw) ($instance.envFromSecret) (dig "stun" "enabled" false $instance) }}
          {{- range $key, $val := $instance.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if $instance.envRaw }}
            {{- with $instance.envRaw }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- range $key, $val := $instance.envFromSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index (splitList "/" $val) 0 }}
                  key: {{ index (splitList "/" $val) 1 }}
          {{- end }}
          {{- if $instance.stun.enabled }}
            - name: NB_ENABLE_STUN
              value: "true"
            - name: NB_STUN_PORTS
              value: {{ join "," $instance.stun.ports | quote }}
          {{- end }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        {{- if $instance.volumes }}
        {{- $instance.volumes | toYaml | nindent 8 }}
        {{- end }}
      {{- with $instance.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $instance.affinity }}
      affinity:
        {{- toYaml $instance.affinity | nindent 8 }}
      {{- end }}
      {{- with $instance.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
