{{- if .Values.relay.instances -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netbird.relay.serviceAccountName" . }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.relay.labels" (dict "root" . "instance" (index .Values.relay.instances 0)) | nindent 4 }}
  {{- with .Values.relay.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
