{{- range $instance := .Values.relay.instances -}}
{{- if $instance.ingress.enabled -}}
{{- $context := dict "root" $ "instance" $instance -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
  namespace: {{ include "netbird.namespace" $ }}
  labels:
    {{- include "netbird.relay.labels" $context | nindent 4 }}
  {{- with $instance.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $instance.ingress.className }}
  ingressClassName: {{ $instance.ingress.className | quote }}
  {{- end }}
  {{- if $instance.ingress.tls }}
  tls:
    {{- toYaml $instance.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range $instance.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "netbird.fullname" $ }}-relay-{{ $instance.name }}
                port:
                  number: {{ $instance.service.port }}
          {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
