{{- if .Values.server.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.fullname" . }}-server
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.server.labels" . | nindent 4 }}
data:
  config.yaml.tmpl: |
    server:
      listenAddress: {{ .Values.server.config.listenAddress | quote }}
      exposedAddress: {{ .Values.server.config.exposedAddress | quote }}
      {{- if .Values.server.config.stunPorts }}
      stunPorts:
        {{- toYaml .Values.server.config.stunPorts | nindent 8 }}
      {{- end }}
      metricsPort: {{ .Values.server.config.metricsPort }}
      healthcheckAddress: {{ .Values.server.config.healthcheckAddress | quote }}
      logLevel: {{ .Values.server.config.logLevel | quote }}
      logFile: {{ .Values.server.config.logFile | quote }}
      {{- if .Values.server.config.tls.enabled }}
      tls:
        certFile: {{ .Values.server.config.tls.certFile | quote }}
        keyFile: {{ .Values.server.config.tls.keyFile | quote }}
        letsencrypt:
          enabled: {{ .Values.server.config.tls.letsencrypt.enabled }}
          dataDir: {{ .Values.server.config.tls.letsencrypt.dataDir | quote }}
          domains:
            {{- toYaml .Values.server.config.tls.letsencrypt.domains | nindent 12 }}
          email: {{ .Values.server.config.tls.letsencrypt.email | quote }}
          awsRoute53: {{ .Values.server.config.tls.letsencrypt.awsRoute53 }}
      {{- end }}
      authSecret: {{ .Values.server.config.authSecret | quote }}
      dataDir: {{ .Values.server.config.dataDir | quote }}
      disableAnonymousMetrics: {{ .Values.server.config.disableAnonymousMetrics }}
      disableGeoliteUpdate: {{ .Values.server.config.disableGeoliteUpdate }}
      auth:
        issuer: {{ .Values.server.config.auth.issuer | quote }}
        localAuthDisabled: {{ .Values.server.config.auth.localAuthDisabled }}
        signKeyRefreshEnabled: {{ .Values.server.config.auth.signKeyRefreshEnabled }}
        {{- if .Values.server.config.auth.dashboardRedirectURIs }}
        dashboardRedirectURIs:
          {{- toYaml .Values.server.config.auth.dashboardRedirectURIs | nindent 8 }}
        {{- end }}
        cliRedirectURIs:
          {{- toYaml .Values.server.config.auth.cliRedirectURIs | nindent 8 }}
        {{- if .Values.server.config.auth.owner }}
        owner:
          email: {{ .Values.server.config.auth.owner.email | quote }}
          password: {{ .Values.server.config.auth.owner.password | quote }}
        {{- end }}
      store:
        engine: {{ .Values.server.config.store.engine | quote }}
        dsn: {{ .Values.server.config.store.dsn | quote }}
        encryptionKey: {{ .Values.server.config.store.encryptionKey | quote }}
      {{- if .Values.server.config.reverseProxy }}
      reverseProxy:
        trustedHTTPProxies:
          {{- toYaml .Values.server.config.reverseProxy.trustedHTTPProxies | nindent 8 }}
        trustedHTTPProxiesCount: {{ .Values.server.config.reverseProxy.trustedHTTPProxiesCount }}
        trustedPeers:
          {{- toYaml .Values.server.config.reverseProxy.trustedPeers | nindent 8 }}
      {{- end }}
{{- end -}}
