fullnameOverride: netbird

server:
  enabled: true
  config:
    exposedAddress: "https://netbird.example.com:443"
    auth:
      issuer: "https://idp.example.com/application/o/netbird/"
      dashboardRedirectURIs:
        - "https://app.example.com/nb-auth"
        - "https://app.example.com/nb-silent-auth"
    store:
      engine: "postgres"
      dsn: "${NB_STORE_DSN}"
  initContainer:
    envFromSecret:
      NB_AUTH_SECRET: netbird-secrets/auth-secret
      NB_ENCRYPTION_KEY: netbird-secrets/encryption-key
      NB_STORE_DSN: netbird-secrets/store-dsn
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    hosts:
      - host: netbird.example.com
        paths:
          - path: /relay
            pathType: ImplementationSpecific
          - path: /ws-proxy/
            pathType: ImplementationSpecific
          - path: /api
            pathType: ImplementationSpecific
          - path: /oauth2
            pathType: ImplementationSpecific
    tls:
      - secretName: netbird-tls
        hosts:
          - netbird.example.com
  ingressGrpc:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      traefik.ingress.kubernetes.io/backend.protocol: h2c
    hosts:
      - host: netbird.example.com
        paths:
          - path: /signalexchange.SignalExchange/
            pathType: ImplementationSpecific
          - path: /management.ManagementService/
            pathType: ImplementationSpecific
          - path: /management.ProxyService/
            pathType: ImplementationSpecific
    tls:
      - secretName: netbird-tls
        hosts:
          - netbird.example.com

dashboard:
  enabled: true
  env:
    NETBIRD_MGMT_API_ENDPOINT: https://netbird.example.com
    NETBIRD_MGMT_GRPC_API_ENDPOINT: https://netbird.example.com
    AUTH_AUTHORITY: https://idp.example.com/application/o/netbird/
    USE_AUTH0: false
    AUTH_SUPPORTED_SCOPES: "openid profile email offline_access api"
  envFromSecret:
    AUTH_CLIENT_ID: netbird-secrets/idp-client-id
    AUTH_AUDIENCE: netbird-secrets/idp-client-id
